[package]
name = "voting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.0.0" }
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
cw20 = "0.12"
cw-core-interface = { version = "0.1.0", path = "../cw-core-interface" } 
cw-core = { path = "../../contracts/cw-core", version = "0.1.0"}
cw-utils = "0.13"
cw-storage-plus = "0.12"
