[package]
name = "cw20-stake"
authors = ["Ben2x4 <Ben2x4@tutanota.com>"]
description = "CW20 token that can be staked and staked balance can be queried at any height"
edition = "2018"
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-storage = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
cw-controllers = { workspace = true }
cw20 = { workspace = true }
cw-utils = { workspace = true }
cw20-base = {  workspace = true, features = ["library"] }
cw2 = { workspace = true }
thiserror = { workspace = true }
cw-paginate-storage = { workspace = true }
cw-ownable = { workspace = true }

cw20-stake-v1 = { workspace = true, features = ["library"] }
cw-utils-v1 = { workspace = true }

[dev-dependencies]
cw-multi-test = { workspace = true }
anyhow = { workspace = true }
