[package]
name = "proposal-hooks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
cosmwasm-std = "1.0.0"
indexable-hooks = { version = "0.1.0", path = "../indexable-hooks" }