[package]
name = "cwd-vote-hooks-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
cwd-vote-hooks = { version = "*", path = "../cwd-vote-hooks" }
syn = { version = "1.0", features = ["derive"] }
quote = "1.0"
proc-macro2 = "1.0"