[package]
name ="cw-admin-factory"
version = "2.0.2"
authors = ["Jake Hartnell", "blue-note", "ekez <ekez@withoutdoing.com>"]
edition = "2021"
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A CosmWasm factory contract for instantiating a contract as its own admin."
license = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-storage = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
thiserror = { workspace = true }
cw-utils = { workspace = true }

[dev-dependencies]
cosmwasm-schema = { workspace = true }
cw-multi-test = { workspace = true }
dao-core = { workspace = true, features = ["library"] }
dao-interface = { workspace = true }
cw20-base = { workspace = true, features = ["library"] }
