[package]
name = "dao-interface"
version = "2.0.1"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package containing interface definitions for DAO DAO DAOs."
documentation = "https://docs.rs/dao-interface"
license = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
dao-macros = { workspace = true }
cw2 = { workspace = true }
cw-hooks = { workspace = true }

[dev-dependencies]
cosmwasm-schema = { workspace = true }
