[package]
name = "cw-hooks"
version = "2.0.3"
edition = "2021"
authors = ["Callum Anderson <callumanderson745@gmail.com>"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package for managing a set of hooks which can be accessed by their index."
license = { workspace = true }

[dependencies]

thiserror = { workspace = true }
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
