chain_cfg: 
  denom: "ujunox"
  prefix: "juno"
  chain_id: "uni-3"
  rpc_endpoint: "https://rpc.uni.juno.deuslabs.fi:443"
  grpc_endpoint: "http://juno-testnet-grpc.polkachu.com:26090"
  gas_prices: 0.1
  gas_adjustment: 1.5

# Add code ids if you dont need to store them:
code_ids:
  "cw20_base": 77
  "cw4_group": 78