[package]
name = "cw-paginate"
version = "2.0.3"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package for paginating cosmwasm maps."
license = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-storage = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true, default-features = false }

[dev-dependencies]
cw-multi-test = { workspace = true }
