[package]
name = "dao-voting-cw721-roles"
authors = ["Jake Hartnell"]
description = "A DAO DAO voting module based on non-transferrable cw721 tokens."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
dao-cw721-extensions = { workspace = true }
dao-dao-macros = { workspace = true }
dao-interface = { workspace = true }
cw721-base = { workspace = true, features = ["library"] }
cw721-controllers = { workspace = true }
cw-ownable = { workspace = true }
cw-paginate-storage = { workspace = true }
cw721 = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw4 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
cw-multi-test = { workspace = true }
cw721-roles = { workspace = true }
anyhow = { workspace = true }
dao-testing = { workspace = true }
