[package]
name = "dao-voting-cw721-staked"
authors = ["CypherApe cypherape@protonmail.com"]
description = "A DAO DAO voting module based on staked cw721 tokens."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
cw-controllers = { workspace = true }
dao-dao-macros = { workspace = true }
dao-interface = { workspace = true }
cw721 = { workspace = true }
cw721-base = { workspace = true, features = ["library"] }
cw721-controllers = { workspace = true }
cw-paginate-storage = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
dao-voting = { workspace = true }
sg-std = { workspace = true }
sg721 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
cw-multi-test = { workspace = true }
dao-testing = { workspace = true }
sg721-base = { workspace = true, features = ["library"] }
sg-multi-test = { workspace = true }
