[package]
name = "dao-pre-propose-base"
authors = ["ekez ekez@withoutdoing.com"]
description = "A package for implementing pre-propose modules."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query WASM exports
library = []

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw2 = { workspace = true }
cw-denom = { workspace = true }
cw-storage-plus = { workspace = true }
cw-utils = { workspace = true }
cw-hooks = { workspace = true }
dao-proposal-hooks = { workspace = true }
dao-interface = { workspace = true }
dao-voting = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
cw-multi-test = { workspace = true }
