[package]
name = "dao-cw-orch"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
wasm_test = []

[dependencies]
cosmwasm-std.workspace = true
cw-orch = { version = "0.22.2" }
cw20-stake = { version = "2.4.2", path = "../../contracts/staking/cw20-stake" }
cw20-stake-external-rewards = { version = "2.4.2", path = "../../contracts/staking/cw20-stake-external-rewards" }
cw20-stake-reward-distributor = { version = "2.4.2", path = "../../contracts/staking/cw20-stake-reward-distributor" }
cw721-base.workspace = true
dao-dao-core = { version = "2.4.2", path = "../../contracts/dao-dao-core" }
dao-interface = { version = "2.4.2", path = "../dao-interface" }
dao-pre-propose-approval-single = { version = "2.4.2", path = "../../contracts/pre-propose/dao-pre-propose-approval-single" }
dao-pre-propose-approver = { version = "2.4.2", path = "../../contracts/pre-propose/dao-pre-propose-approver" }
dao-pre-propose-multiple = { version = "2.4.2", path = "../../contracts/pre-propose/dao-pre-propose-multiple" }
dao-pre-propose-single = { version = "2.4.2", path = "../../contracts/pre-propose/dao-pre-propose-single" }
dao-proposal-condorcet = { version = "2.4.2", path = "../../contracts/proposal/dao-proposal-condorcet" }
dao-proposal-hook-counter = { version = "2.4.2", path = "../../contracts/test/dao-proposal-hook-counter" }
dao-proposal-multiple = { version = "2.4.2", path = "../../contracts/proposal/dao-proposal-multiple" }
dao-proposal-single = { version = "2.4.2", path = "../../contracts/proposal/dao-proposal-single" }
dao-proposal-sudo = { version = "2.4.2", path = "../../contracts/test/dao-proposal-sudo" }
dao-test-custom-factory = { version = "2.4.2", path = "../../contracts/test/dao-test-custom-factory" }
dao-voting-cw20-balance = { version = "2.4.2", path = "../../contracts/test/dao-voting-cw20-balance" }
dao-voting-cw20-staked = { version = "2.4.2", path = "../../contracts/voting/dao-voting-cw20-staked" }
dao-voting-cw4 = { version = "2.4.2", path = "../../contracts/voting/dao-voting-cw4" }
dao-voting-cw721-roles = { version = "2.4.2", path = "../../contracts/voting/dao-voting-cw721-roles" }
dao-voting-cw721-staked = { version = "2.4.2", path = "../../contracts/voting/dao-voting-cw721-staked" }
dao-voting-token-staked = { version = "2.4.2", path = "../../contracts/voting/dao-voting-token-staked" }
serde.workspace = true
