[package]
name = "ictest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
localic-std = {git = "https://github.com/strangelove-ventures/interchaintest", branch = "v7" }
# localic-std = {path = "/home/reece/Desktop/Programming/Go/interchaintest/local-interchain/rust/localic-std"} # TODO: TEMP
cosmwasm-std = "1.4.0"
reqwest = { version = "0.11.20", features = ["blocking", "json"]}
serde_json = { version = "1.0.107" }

[workspace]
