[package]
name = "cw-wormhole"
authors = ["ekez <ekez@withoutdoing.com>"]
description = "A CosmWasm map that allows incrementing and decrementing values from the past."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
