[package]
name = "cwd-hooks"
version = "0.2.0"
edition = "2021"
authors = ["Callum Anderson <callumanderson745@gmail.com>"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package for managing a set of hooks which can be accessed by their index."

[dependencies]
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
cosmwasm-std = "1.0.0"
cw-storage-plus = "0.13"
