[package]
name = "dao-testing"
authors = ["ekez ekez@withoutdoing.com"]
description = "Testing helper functions and interfaces for testing DAO modules."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

# This crate depends on multi-test and rand. These are not features in
# wasm builds of cosmwasm. Despite this crate only being used as a dev
# dependency, because it is part of the workspace it will always be
# compiled. There is no good way to remove a member from a workspace
# conditionally. As such, we don't compile anything here if we're
# targeting wasm.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-multi-test = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw20-base = { workspace = true }
cw4 = { workspace = true }
cw4-group = { workspace = true }
rand = { workspace = true }

cw-core-v1 = { workspace = true, features = ["library"] }
cw-hooks = { workspace = true }
cw-proposal-single-v1 = { workspace = true }
cw-vesting = { workspace = true }
cw20-stake = { workspace = true }
cw721-base = { workspace = true }
dao-dao-core = { workspace = true, features = ["library"] }
dao-interface = { workspace = true }
dao-pre-propose-multiple = { workspace = true }
dao-pre-propose-single = { workspace = true }
dao-proposal-condorcet = { workspace = true }
dao-proposal-single = { workspace = true }
dao-voting = { workspace = true }
dao-voting-cw20-balance = { workspace = true }
dao-voting-cw20-staked = { workspace = true }
dao-voting-cw4 = { workspace = true }
dao-voting-cw721-staked = { workspace = true }
dao-voting-native-staked = { workspace = true }
voting-v1 = { workspace = true }
stake-cw20-v03 = { workspace = true }
