[package]
name = "dao-testing"
authors = [
  "ekez ekez@withoutdoing.com",
  "Jake Hartnell <no-reply@no-reply.com>",
  "noah <noah@daodao.zone>",
]
description = "Testing helper functions and interfaces for testing DAO modules."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[features]
# use test tube feature to enable test-tube integration tests, for example
# cargo test --features "test-tube"
test-tube = []
# when writing tests you may wish to enable test-tube as a default feature
# default = ["test-tube"]

# This crate depends on multi-test and rand. These are not features in
# wasm builds of cosmwasm. Despite this crate only being used as a dev
# dependency, because it is part of the workspace it will always be
# compiled. There is no good way to remove a member from a workspace
# conditionally. As such, we don't compile anything here if we're
# targeting wasm.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-multi-test = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw20-base = { workspace = true }
cw4 = { workspace = true }
cw4-group = { workspace = true }
osmosis-std = { workspace = true }
osmosis-test-tube = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

btsg-ft-factory = { workspace = true }
cw-admin-factory = { workspace = true }
cw-fund-distributor = { workspace = true }
cw-hooks = { workspace = true }
cw-payroll-factory = { workspace = true }
cw-token-swap = { workspace = true }
cw-vesting = { workspace = true }
cw20-stake = { workspace = true }
cw20-stake-external-rewards = { workspace = true }
cw20-stake-reward-distributor = { workspace = true }
cw721-base = { workspace = true }
cw721-roles = { workspace = true }
cw-tokenfactory-issuer = { workspace = true }
dao-dao-core = { workspace = true }
dao-interface = { workspace = true }
dao-migrator = { workspace = true }
dao-pre-propose-approver = { workspace = true }
dao-pre-propose-multiple = { workspace = true }
dao-pre-propose-single = { workspace = true }
dao-pre-propose-approval-single = { workspace = true }
dao-proposal-condorcet = { workspace = true }
dao-proposal-single = { workspace = true }
dao-proposal-multiple = { workspace = true }
dao-proposal-sudo = { workspace = true }
dao-rewards-distributor = { workspace = true }
dao-test-custom-factory = { workspace = true }
dao-voting = { workspace = true }
dao-voting-cw20-balance = { workspace = true }
dao-voting-cw20-staked = { workspace = true }
dao-voting-cw4 = { workspace = true }
dao-voting-cw721-staked = { workspace = true }
dao-voting-cw721-roles = { workspace = true }
dao-voting-onft-staked = { workspace = true }
dao-voting-token-staked = { workspace = true }
dao-proposal-hook-counter = { workspace = true }

# v1 migration
cw-core-v1 = { workspace = true }
cw-proposal-single-v1 = { workspace = true }
cw4-voting-v1 = { workspace = true }
cw20-stake-v1 = { workspace = true }
cw20-stake-external-rewards-v1 = { workspace = true }
cw20-stake-reward-distributor-v1 = { workspace = true }
stake-cw20-v03 = { workspace = true }
voting-v1 = { workspace = true }

# v2.4.1 migration
dao-dao-core-v241 = { workspace = true }
dao-interface-v241 = { workspace = true }
dao-pre-propose-approval-single-v241 = { workspace = true }
dao-pre-propose-single-v241 = { workspace = true }
dao-pre-propose-multiple-v241 = { workspace = true }
dao-proposal-single-v241 = { workspace = true }
dao-proposal-multiple-v241 = { workspace = true }
dao-voting-cw4-v241 = { workspace = true }
dao-voting-v241 = { workspace = true }
