[package]
name = "cw-denom"
authors = ["ekez ekez@withoutdoing.com"]
description = "A package for validation and handling of cw20 and native Cosmos SDK denominations."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }

thiserror = { workspace = true }
cw20 = { workspace = true }

[dev-dependencies]
cw20-base = { workspace = true }
cw-multi-test = { workspace = true }
