[package]
name = "cw-abc"
version = "0.0.1"
authors = [
    "Ethan Frey <ethanfrey@users.noreply.github.com>",
    "Jake Hartnell",
    "Adair <adairrr@users.noreply.github.com>",
]
edition = { workspace = true }
description = "Implements an Augmented Bonding Curve"
license = "Apache-2.0"
repository = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []
# interface = ["dep:cw-orch"] # Adds the dependency when the feature is enabled

[dependencies]
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw-storage-plus = { workspace = true }
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
thiserror = { workspace = true }
# TODO move to workspace
cw-address-like = "1.0.4"
rust_decimal = "1.14.3"
integer-sqrt = "0.1.5"
integer-cbrt = "0.1.2"
getrandom = { version = "0.2", features = ["js"] }
token-bindings = { workspace = true }
cw-ownable = { workspace = true }
cw-paginate-storage = { workspace = true }
cw-tokenfactory-issuer = { workspace = true, features = ["library"] }
# cw-orch = { version = "0.13.3", optional = true }

[dev-dependencies]
# TODO move to workspace?
speculoos = "0.11.0"
anyhow = { workspace = true }
cw-multi-test = { workspace = true }
dao-testing = { workspace = true }
osmosis-test-tube = { workspace = true }

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
