[package]
name = "dao-proposal-hooks"
version = "2.0.3"
edition = "2021"
authors = ["Callum Anderson <callumanderson745@gmail.com>"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package for managing proposal hooks."
license = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-hooks = { workspace = true }
dao-voting = { workspace = true }
