name: Contracts

on:
  push:
    branches:
      - feat/ci-deploy
    #paths: "contracts/**"

jobs:
  compile:
    runs-on: ubuntu-20.04
    container:
      image: cosmwasm/workspace-optimizer:0.12.6
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Optimize
        run: optimize_workspace.sh
      - name: Store contracts in cache
        uses: actions/cache@v3
        with:
          path: artifacts
          key: artifacts-contracts

  upload:
    needs: compile
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cosmoscontracts/juno:v6.0.0
    steps:
      - name: Calibrate the Stargate ðŸª
        env:
          JUNO_CHAIN_ID: ${{ secrets.JUNO_CHAIN_ID }}
          JUNO_RPC_NODE: ${{ secrets.JUNO_RPC_NODE }}
        run: |
          junod config chain-id "$JUNO_CHAIN_ID"
          junod config node "$JUNO_RPC_NODE"
      - name: Assume upload identity
        env:
          DAO_UPLOAD_NINJA: ${{ secrets.DAO_UPLOAD_NINJA}}
        run: |
          echo "$DAO_UPLOAD_NINJA" | base64 -d > ðŸ¥·.sh
          sh ðŸ¥·.sh
        name: Upload to community computer
        with:
          path: artifacts
        run: |
          ls
          junod version
        #     junod tx wasm store cw_core.wasm --from <ngmi wallet> --chain-id juno-1 --gas-prices 0.1ujuno --gas auto --gas-adjustment 1.3 -b block